---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - babel

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true
  browser: true


extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign: ["error", { props: true, ignorePropertyModificationsFor: ["state", "postsContainer", "feedsContainer"] }]